### ISSUE TITLE
FastAPI Swagger UI Authentication

### ISSUE THREAD

**Issue by kennedy** [Kigstn/BungIO#3]
Hello @Kigstn,
I am using FastAPI and attempting to take advantage of the Swagger Doc UI to authenticate with bungie while developing my app. I know this is [out of scope](https://github.com/Kigstn/BungIO/blob/master/docs/src/Guides/auth.md), but when you used FastAPI as an example, I thought you might have solved my issue.

```python
from fastapi.security import OAuth2AuthorizationCodeBearer

bungie_secrets = dotenv_values(".env.secret")

client = MyClient(
    bungie_client_id=bungie_secrets.get("client_id"),
    bungie_client_secret=bungie_secrets.get("client_secret"),
    bungie_token=bungie_secrets.get("token"),
)

authentication = OAuth2AuthorizationCodeBearer(
    authorizationUrl=client.get_auth_url(state=secrets.token_urlsafe(20)),
    tokenUrl="https://www.bungie.net/platform/app/oauth/token/",
)

app: FastAPI = FastAPI(
    swagger_ui_init_oauth={
        "clientId": bungie_secrets.get("client_id"),
        "clientSecret": bungie_secrets.get("client_secret"),
    },
)

# call this from your website
@app.get("/auth/")
async def authenticate(state: str, code: str, token: str = Security(authentication)):
    """Receive information from bungie authentication"""

    # generate an access token with the code
    # this will call `Client.on_token_update` we defined above
    auth = await client.generate_auth(code=code)

    return {"membership_id": auth.membership_id}
```

In the Swagger Docs, I was able to get the `authenticate` button to initiate the oauth flow with bungie. Unfortunately, when it gets redirected back to my page I am getting a `401` error with `{"detail":"Not authenticated"}`

![image](https://github.com/Kigstn/BungIO/assets/854543/a5585bbc-c7a0-475e-8a32-8054a5dec06a), 

Bungie only likes https so ive been tunneling my app via `ngrok http 8000`, and put the redirect url to the auto generated ngrok endpoint.

Do you have any advice on what my problem is and how to take better advantage of FastAPI's Swagger docs? I think this would be a good additional documentation for the auth example.

Edit: Further details about using NGROK

**Comment by Kigstn** [comment]
Hmm, sadly I haven't played around with that before. I'll take a look next week - will report back my findings :)

**Comment by Kigstn** [comment]
@kennedy 
From looking at the fastapi code, it looks like you are using it wrong / `OAuth2AuthorizationCodeBearer` is not working correctly / bungie is simply not following the oauth standart well enough. For example, bungie does not allow passing a redirect url as a query param.

Sadly it's kind of annoying to figure out what exactly fastapi does in the background since `OAuth2AuthorizationCodeBearer` is not documented anywhere (yet)...

As a workaround, if you change
```py
authentication = OAuth2AuthorizationCodeBearer(
    authorizationUrl=client.get_auth_url(state=secrets.token_urlsafe(20)),
    tokenUrl="https://www.bungie.net/platform/app/oauth/token/",
)
```
to 
```py
authentication = OAuth2AuthorizationCodeBearer(
    authorizationUrl=client.get_auth_url(state=secrets.token_urlsafe(20)),
    tokenUrl="https://www.bungie.net/platform/app/oauth/token/",
    auto_error=False,
)
```
fastapi won't error out and you can complete the auth flow as you did - since it mainly relies on bungio not fastapi :)
